image: Ubuntu2004

stack: jdk 11

branches:
  only:
    - main
    - master

install:
  - sudo apt-get update
  - sudo apt-get install -y google-chrome-stable
  - java -version
  - google-chrome --version
  - java -jar ./artifacts/app-card-delivery.jar &

build_script:
  - ./gradlew test --info -Dselenide.headless=true

test: off
