image: Ubuntu2004

stack: jdk 11

branches:
  only:
    - main
    - master

install:
  - java -jar ./artifacts/app-card-delivery.jar &

build_script:
  - ./gradlew test --info -Dselenide.headless=true

test: off
